---
- name: Verify
  hosts:
    - subjects
  tasks:
    - name: Check if HashiCorp Packer package is installed
      check_mode: true
      become: true
      ansible.builtin.package:
        name:
          - packer
        state: present
      register: _packer_package
      ignore_errors: true

    - name: Check if HashiCorp Vault package is installed
      check_mode: true
      become: true
      ansible.builtin.package:
        name:
          - vault
        state: present
      register: _vault_package
      ignore_errors: true

    - name: Verify HashiCorp Packer and/or Vault package is installed
      ansible.builtin.assert:
        that:
          - (_packer_package is changed and _packer_package is success) or
            (_vault_package is changed and _vault_package is success)
        fail_msg: HashiCorp Packer or Vault package can not be installed.
        success_msg: HashiCorp Packer and/or Vault package can be installed.
